name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-e2e:
    name: Test E2E (Xcode ${{ matrix.xcode }})
    runs-on: macos-14
    strategy:
      matrix:
        xcode:
        # - '13.1' # Swift 5.5
        # - '13.2' # Swift 5.5.2
        - '15.2' # Swift 5.9.2
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Project
      run: Sources/MockingbirdAutomationCli/buildAndRun.sh configure load --overwrite
    - name: Test
      env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      run: Sources/MockingbirdAutomationCli/buildAndRun.sh test e2e

  test-example-project:
    name: Test Example Project (${{ matrix.type }})
    runs-on: macos-14
    strategy:
      matrix:
        type:
        # - cocoapods
        # - carthage
        - spm-project
        - spm-package
    steps:
    - uses: actions/checkout@v2
    - name: Test
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      run: Sources/MockingbirdAutomationCli/buildAndRun.sh test example ${{ matrix.type }}

  test-cli-launcher:
    name: Test CLI Launcher
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Test
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        MKB_ARTIFACTS_URL: https://github.com/birdrides/mockingbird/releases/download/0.19.0/<FILE>
      run: ./mockingbird version

  # build-cocoapods:
  #   name: Build CocoaPods
  #   runs-on: macos-14
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build
  #     env:
  #       GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  #     run: pod lib lint MockingbirdFramework.podspec

  # build-carthage:
  #   name: Build Carthage
  #   runs-on: macos-14
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set Up Project
  #     run: Sources/MockingbirdAutomationCli/buildAndRun.sh configure unload --keep MockingbirdFramework
  #   - name: Build Release
  #     run: Sources/MockingbirdAutomationCli/buildAndRun.sh build

  build-swiftpm:
    name: Build SwiftPM
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      run: swift build --configuration debug
    - name: Build Release
      run: swift build --configuration release
